sudo: required
language: generic
services:
        -docker

install:
        - .travis/cabal_install
            
before_install:
        -docker build -t oalfatyan/docker-react -f dockerfile.dev .

script: |

script:
    
    -docker run -e CI=true oalfatyan/docker-react npm run test
