sudo: required
language: generic
services:
    -docker


before_install:
    -docker build -t oalfatyan/docker-react -f dockerfile.dev .


script:
    
    - docker run -e CI=true oalfatyan/docker-react npm run test
