sudo: required
services:
    -docker


before_install:
    -docker build -t oalfatyan/docker-react -f dockerfile.dev .


script:
    - docker run -e  oalfatyan/docker-react npm run test -- --coverage
